# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

version: 2.1
orbs:
  node: circleci/node@7.1.0
  aws-ecr: circleci/aws-ecr@9.5.1
  aws-cli: circleci/aws-cli@5.3.2

base: &base
  resource_class: small
  docker:
    - image: cimg/node:23.6.1

commands:
  checkout_and_install:
    steps:
      - checkout
      - node/install-packages:
          cache-only-lockfile: false
          cache-path: ./node_modules
          include-branch-in-cache-key: false
      - run:
          command: make install-tools

jobs:
  lint:
    <<: *base
    description: Run lint checks
    steps:
      - checkout_and_install
      - run:
          command: npm run lint

  test:
    <<: *base
    description: Run lint checks
    steps:
      - checkout_and_install
      - run:
          command: npm run test

  build-and-push:
    description: Run image and push to remote ECR
    resource_class: small
    docker:
      - image: cimg/base:2025.05
    steps:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: "${AWS_ROLE_ARN}"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"


workflows:
  build-and-test:
    jobs:
      - lint
      - test

  build-and-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
