# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

version: 2.1
orbs:
  node: circleci/node@7.1.0

base: &base
  resource_class: small
  docker:
    - image: cimg/node:23.6.1

commands:
  checkout_and_install:
    steps:
      - checkout
      - node/install-packages:
          cache-only-lockfile: false
          cache-path: ./node_modules
          include-branch-in-cache-key: false
      - run:
          command: make install-tools

jobs:
  lint:
    <<: *base
    description: Run lint checks
    steps:
      - checkout_and_install
      - run:
          command: npm run lint

  test:
    <<: *base
    description: Run lint checks
    steps:
      - checkout_and_install
      - run:
          command: npm run test


workflows:
  build-and-test:
    jobs:
      - lint
      - test
